services:
  apache:
    build:
      context: ./webservers
      dockerfile: ./apache/Dockerfile
      args:
        APP_ENV: ${APP_ENV}
    container_name: '${APP_NAME}-php-apache-server'
    ports:
      - '${HTTPS_APP_PORT}:${HTTPS_APP_PORT}'
      - '${SECONDARY_APP_PORT}:${SECONDARY_APP_PORT}'
    environment:
      APP_ENV: ${APP_ENV}
      APP_NAME: ${APP_NAME}
      APP_SECRET: ${APP_SECRET}x
      HTTPS_APP_PORT: ${HTTPS_APP_PORT}
      SECONDARY_APP_PORT: ${SECONDARY_APP_PORT}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      REDIS_INTERNAL_PORT: ${REDIS_INTERNAL_PORT}
      ELASTIC_SEARCH_HTTP_AUTH_PASSWORD: ${ELASTIC_SEARCH_HTTP_AUTH_PASSWORD}
      ELASTIC_VERSION: ${ELASTIC_VERSION}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      PHP_MEMORY_LIMIT: ${PHP_MEMORY_LIMIT}
    volumes:
      - ../app:/var/www/html:cached
      - ../SSL:/etc/ssl:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      php-cli:
        condition: service_healthy
      maria-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      es01:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - HomeAppProjectNetwork

  php-cli:
    build:
      context: ./webservers
      dockerfile: ./php-cli/Dockerfile
    container_name: '${APP_NAME}-php-cli-queue-proccessor'
    environment:
      APP_ENV: ${APP_ENV}
      APP_NAME: ${APP_NAME}
      HTTPS_APP_PORT: ${HTTPS_APP_PORT}
      SECONDARY_APP_PORT: ${SECONDARY_APP_PORT}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      REDIS_INTERNAL_PORT: ${REDIS_INTERNAL_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      ELASTIC_SEARCH_HTTP_AUTH_PASSWORD: ${ELASTIC_SEARCH_HTTP_AUTH_PASSWORD}
      ELASTIC_ENABLED: ${ELASTIC_ENABLED}
      ELASTIC_VERSION: ${ELASTIC_VERSION}
    healthcheck:
      test: ["CMD", "php", "-v"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - ../app:/var/www/html:cached
      - ../SSL:/etc/ssl/custom:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      maria-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      es01:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - HomeAppProjectNetwork

  maria-db:
    build:
      context: ./mariadb
      dockerfile: ./Dockerfile
    container_name: '${APP_NAME}-mariadb'
    environment:
      APP_ENV: ${APP_ENV}
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_USER : ${MARIADB_USER}
      MYSQL_PASSWORD: ${MARIADB_PASSWORD}
      MYSQL_DATABASE: ${MARIADB_DATABASE}
      MARIADB_INTERNAL_PORT: ${MARIADB_INTERNAL_PORT}
    volumes:
      - ./mariadb/db_data:/var/lib/mysql:rw,delegated
      - ../SSL/custom:/etc/mysql/ssl:ro
      - ./mariadb/dumps:/dumps
      - ${BACKUP_DIRECTORY}:/backup:rw,delegated
      - /etc/timezone:/etc/timezone:ro
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $MARIADB_USER --password=$MARIADB_PASSWORD
      interval: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - HomeAppProjectNetwork

  yarn:
    build:
      context: ./yarn
      dockerfile: ./Dockerfile
    container_name: '${APP_NAME}-yarn'
    environment:
      APP_ENV: ${APP_ENV}
    volumes:
      - ../app:/home/node/app/src:cached
    networks:
      - HomeAppProjectNetwork
    depends_on:
      - apache

  rabbitmq:
    build:
      context: ./rabbitmq
      dockerfile: ./Dockerfile
    container_name: '${APP_NAME}-rabbitmq'
    environment:
        RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
        RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - '${RABBIT_MQ_INTERFACE_PORT}:15672'
    volumes:
        - ./rabbitmq/data/:/var/lib/rabbitmq:rw,delegated
        - ./rabbitmq/HomeAppRabbitMQ.json:/etc/rabbitmq/definitions.json:ro
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    restart: unless-stopped
    networks:
      - HomeAppProjectNetwork

  redis:
    build:
      context: ./redis
      dockerfile: ./Dockerfile
    container_name: '${APP_NAME}-redis'
    environment:
      REDIS_INTERNAL_PORT: ${REDIS_INTERNAL_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: unless-stopped
    networks:
      - HomeAppProjectNetwork

  es01:
    container_name: ${APP_NAME}-es01
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    ports:
      - ${ELASTICSEARCH_EXTERNAL_PORT}:9200
    environment:
      - node.name=es01
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01,es02
      - cluster.name=docker-cluster
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g -Dcom.sun.management.jmxremote=false -XX:+UseContainerSupport"
      - xpack.license.self_generated.type=basic
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.keystore.path=/usr/share/elasticsearch/config/certs/es01/es01.p12
      - xpack.security.transport.ssl.truststore.path=/usr/share/elasticsearch/config/certs/es01/es01.p12
      - xpack.security.transport.ssl.keystore.password=''
      - xpack.security.transport.ssl.truststore.password=''
    volumes:
      - 'data01:/usr/share/elasticsearch/data'
      - 'certs:/usr/share/elasticsearch/config/certs:ro'

    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: curl -s -u "elastic:$ELASTIC_PASSWORD" http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=50s || exit 1
      interval: 15s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    networks:
      - HomeAppProjectNetwork

  es02:
    container_name: ${APP_NAME}-es02
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    environment:
      - node.name=es02
      - cluster.name=docker-cluster
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01,es02
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g -Dcom.sun.management.jmxremote=false -XX:+UseContainerSupport"
      - xpack.license.self_generated.type=basic
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.keystore.path=/usr/share/elasticsearch/config/certs/es02/es02.p12
      - xpack.security.transport.ssl.truststore.path=/usr/share/elasticsearch/config/certs/es02/es02.p12
      - xpack.security.transport.ssl.keystore.password=''
      - xpack.security.transport.ssl.truststore.password=''
    volumes:
      - 'data02:/usr/share/elasticsearch/data'
      - 'certs:/usr/share/elasticsearch/config/certs:ro'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: curl -s -u "elastic:$ELASTIC_PASSWORD" http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=50s || exit 1
      interval: 15s
      timeout: 10s
      retries: 5
    depends_on:
      - es01
    restart: unless-stopped
    networks:
      - HomeAppProjectNetwork

volumes:
  data01:
  data02:
  certs:

networks:
  HomeAppProjectNetwork:
