version: '3.9'
services:
  apache:
    build:
      context: ./apache
      dockerfile: ./Dockerfile
      args:
        APP_ENV: ${APP_ENV}
    container_name: '${APP_NAME}-php-apache-server'
    ports:
      - '${HTTPS_APP_PORT}:443'
    environment:
      APP_ENV: ${APP_ENV}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
    volumes:
      - ../SymfonyReact:/var/www/html
      - ../SSL:/etc/ssl
      - ./apache/sites-enabled:/etc/apache2/sites-enabled
      - ./apache/php-config/php.ini:/usr/local/etc/php/conf.d/extra-php-config.ini
      - ./apache/logs:/etc/logs
    depends_on:
      maria-db:
        condition: service_healthy
    networks:
      - HomeAppProjectNetwork

  maria-db:
    build:
      context: ./mariadb
      dockerfile: ./Dockerfile
    container_name: '${APP_NAME}-mariadb'
    restart: always
    environment:
      APP_ENV: ${APP_ENV}
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_USER : ${MARIADB_USER}
      MYSQL_PASSWORD: ${MARIADB_PASSWORD}
      MYSQL_DATABASE: ${MARIADB_DATABASE}
    volumes:
      - ./mariadb/db_data:/var/lib/mysql
      - ./mariadb/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mariadb/setup.sql:/docker-entrypoint-initdb.d/init.sql:rw,delegated
      - ./mariadb/50config/50-client.cnf:/etc/mysql/mariadb.conf.d/50-client.cnf
      - ./mariadb/50config/50-server.cnf:/etc/mysql/mariadb.conf.d/50-server.cnf
      - ../SSL:/etc/mysql/ssl
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $MARIADB_USER --password=$MARIADB_PASSWORD
      interval: 5s
      retries: 5
    networks:
      - HomeAppProjectNetwork

  yarn:
    build:
      context: ./yarn
    container_name: '${APP_NAME}-yarn'
    working_dir: /home/node/app/src
    environment:
      APP_ENV: ${APP_ENV}
    volumes:
      - ../SymfonyReact:/home/node/app/src
    networks:
      - HomeAppProjectNetwork
    depends_on:
      - apache

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: '${APP_NAME}-rabbitmq'
    ports:
      - '${RABBIT_MQ_INTERFACE_PORT}:15672'
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
        - ./rabbitmq/data/:/var/lib/rabbitmq:rw,delegated
        # - ./rabbitmq/HomeAppRabbitMQ.json:/opt/definitions.json:ro
        - ./rabbitmq/HomeAppRabbitMQ.json:/etc/rabbitmq/definitions.json:ro
    networks:
      - HomeAppProjectNetwork

networks:
  HomeAppProjectNetwork:
