version: '3.9'
services:
  apache:
    build:
      context: ./apache
      dockerfile: ./Dockerfile
      args:
        APP_ENV: ${APP_ENV}
    container_name: '${APP_NAME}-php-apache-server'
    ports:
      - '${HTTPS_APP_PORT}:443'
    environment:
      APP_ENV: ${APP_ENV}
      APP_NAME: ${APP_NAME}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
    volumes:
      - ../SymfonyReact:/var/www/html:cached
      - ../SSL:/etc/ssl:ro
    depends_on:
      maria-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - HomeAppProjectNetwork

  maria-db:
    build:
      context: ./mariadb
      dockerfile: ./Dockerfile
    container_name: '${APP_NAME}-mariadb'
    restart: unless-stopped
    environment:
      APP_ENV: ${APP_ENV}
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_USER : ${MARIADB_USER}
      MYSQL_PASSWORD: ${MARIADB_PASSWORD}
      MYSQL_DATABASE: ${MARIADB_DATABASE}
    volumes:
      - ./mariadb/db_data:/var/lib/mysql:rw,delegated
      - ../SSL:/etc/mysql/ssl:ro
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $MARIADB_USER --password=$MARIADB_PASSWORD
      interval: 5s
      retries: 5
    networks:
      - HomeAppProjectNetwork

  yarn:
    build:
      context: ./yarn
      dockerfile: ./Dockerfile
    container_name: '${APP_NAME}-yarn'
    environment:
      APP_ENV: ${APP_ENV}
    volumes:
      - ../SymfonyReact:/home/node/app/src:cached
    networks:
      - HomeAppProjectNetwork
    depends_on:
      - apache

  rabbitmq:
    build:
      context: ./rabbitmq
      dockerfile: ./Dockerfile
    container_name: '${APP_NAME}-rabbitmq'
    ports:
      - '${RABBIT_MQ_INTERFACE_PORT}:15672'
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
        - ./rabbitmq/data/:/var/lib/rabbitmq:rw,delegated
        - ./rabbitmq/HomeAppRabbitMQ.json:/etc/rabbitmq/definitions.json:ro
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    restart: unless-stopped
    networks:
      - HomeAppProjectNetwork

networks:
  HomeAppProjectNetwork:
