version: '3.9'

services:
  apache:
    build:
      context: ./apache
      dockerfile: ./Dockerfile
      args:
        APP_ENV: prod
    container_name: '${APP_NAME}-php-apache-server'
    ports:
      - '127.0.0.1:${HTTPS_APP_PORT}:443'
      - 9000
    working_dir: /var/www/html
    environment:
      - 'DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASS}@db_server:3306/${MYSQL_DB}?serverVersion=10.6' #@DEV look into
      - 'APP_ENV=${APP_ENV}'
      # - WSLIP=${WSLIP}
    volumes:
      - ../SymfonyReact:/var/www/html
      - ../SSL:/etc/ssl
      - ./apache/sites-enabled:/etc/apache2/sites-enabled
      - ./apache/php.ini:/usr/local/etc/php/conf.d/extra-php-config.ini
      - ./apache/logs:/etc/logs
    depends_on:
      maria-db:
        condition: service_healthy
    networks:
      - HomeAppProjectNetwork

  maria-db:
    build:
      context: ./mariadb
      dockerfile: ./Dockerfile
    container_name: '${APP_NAME}-mariadb'
    restart: always
#    ports:
#      - '127.0.0.1:${DB_PORT}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASS}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASS}'
      MYSQL_DATABASE: '${MYSQL_DB}'
    volumes:
      - ./mariadb/db_data:/var/lib/mysql
      - ./mariadb/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mariadb/setup.sql:/docker-entrypoint-initdb.d/init.sql:rw,delegated
      - ./mariadb/50config/50-client.cnf:/etc/mysql/mariadb.conf.d/50-client.cnf
      - ../SSL:/etc/mysql/ssl
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 5s
      retries: 5
    networks:
      - HomeAppProjectNetwork

  yarn:
    build:
      context: ./yarn
    container_name: '${APP_NAME}-yarn'
    ports:
      - 8080:8080
    working_dir: /home/node/app/src
    environment:
      - 'APP_ENV=${APP_ENV}'
    volumes:
      - ../SymfonyReact:/home/node/app
    networks:
      - HomeAppProjectNetwork

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: '${APP_NAME}-rabbitmq'
    ports:
      - '127.0.0.1:${RABBIT_MQ_INTERFACE_PORT}:15672'
    volumes:
        - ./rabbitmq/data/:/var/lib/rabbitmq
        - ./rabbitmq/log/:/var/log/rabbitmq
    networks:
      - HomeAppProjectNetwork

networks:
  HomeAppProjectNetwork:
