parameters:
services:
  _defaults:
      public: true
      autowire: true

#  Symfony\Contracts\HttpClient\HttpClientInterface: ~
#  Symfony\Contracts\HttpClient\HttpClientInterface:
#    class: '@Symfony\Contracts\HttpClient\HttpClientInterface'
#    synthetic: true

#  test.Symfony\Contracts\HttpClient\HttpClientInterface:
#  test.Symfony\Contracts\HttpClient\HttpClientInterface:
