controllers:
    resource: ../../src/Controller/
    type: annotation

esp-device-sensors:
    resource: ../../src/ESPDeviceSensor/Controller
#    prefix: /HomeApp/api/sensors
    type: annotation

devices:
    resource: ../../src/Devices/Controller
#    prefix: /api/devices
    type: annotation

user:
    resource: ../../src/User/Controller
    #    prefix: /api/devices
    type: annotation

user-interface:
    resource: ../../src/UserInterface/Controller
    #    prefix: /api/devices
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
