esp-device-sensors:
    resource: ../../src/Sensors/Controller
    type: annotation

devices:
    resource: ../../src/Devices/Controller
    type: annotation

user:
    resource: ../../src/User/Controller
    type: annotation

user-interface:
    resource: ../../src/UserInterface/Controller
    type: annotation

authentication:
    resource: ../../src/Authentication/Controller
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
