old_sound_rabbit_mq:
  connections:
    default:
      host:     'localhost'
      port:     5672
      user:     'guest'
      password: 'guest'
      vhost:    '/'
      lazy:     false
      connection_timeout: 3
      read_write_timeout: 3

      # requires php-amqplib v2.4.1+ and PHP5.4+
      keepalive: false

      # requires php-amqplib v2.4.1+
      heartbeat: 0

      #requires php_sockets.dll
      use_socket: true # default false

#    another:
      # A different (unused) connection defined by an URL. One can omit all parts,
      # except the scheme (amqp:). If both segment in the URL and a key value (see above)
      # are given the value from the URL takes precedence.
      # See https://www.rabbitmq.com/uri-spec.html on how to encode values.
#      url: 'amqp://guest:password@localhost:5672/vhost?lazy=1&connection_timeout=6'
      producers:
        upload_current_reading_sensor_data:
          class: App\Producers\SensorProducers
          connection: default
          exchange_options: { name: 'current-reading-upload-sensor-data', type: direct }
#          service_alias: home_app_service # no alias by default
      consumers:
        upload_current_reading_sensor_data:
          connection: default
          exchange_options: { name: 'current-reading-upload-sensor-data', type: direct }
          queue_options: { name: 'upload-current-reading-sensor-data' }
          callback: upload_sensor_current_reading_service



#old_sound_rabbit_mq:
#  connections:
#    default:
#      url: '%env(RABBITMQ_URL)%'
#      lazy: false
#      connection_timeout: 3
#      read_write_timeout: 3
#
#      # requires php-amqplib v2.4.1+ and PHP5.4+
#    #        keepalive: false
#
#    # requires php-amqplib v2.4.1+
#    #        heartbeat: 0
#
#    #requires php_sockets.dll
#    use_socket: true # default false
#
#  producers:
#    upload_current_reading_sensor_data:
#      connection: default
#      exchange_options: { name: 'current-reading-upload-sensor-data', type: direct }
#  #                service_alias: home_app_service # no alias by default
#  consumers:
#    upload_current_reading_sensor_data:
#      connection: default
#      exchange_options: { name: 'current-reading-upload-sensor-data', type: direct }
#      queue_options: { name: 'upload-current-reading-sensor-data' }
#      callback: App\AMQP\UploadCurrentReadingSensorDataConsumer

#    producers:
#        # use 'old_sound_rabbit_mq.task_producer' service to send data.
#        task:
#            connection:       default
#            exchange_options: { name: 'task', type: direct }
#    consumers:
#        task:
#            connection:       default
#            exchange_options: { name: 'task', type: direct }
#            queue_options:    { name: 'task'}
#            callback:         App\Consumer\TaskConsumer
