api_login_check:
    path: /HomeApp/api/login_check

sensor_api_login_check:
  path: /HomeApp/api/device/login_check

gesdinet_jwt_refresh_token:
  path:       /HomeApp/api/token/refresh
  controller: gesdinet.jwtrefreshtoken::refresh

##@Dev work on removing
#add_new_device_controller:
#  path: /HomeApp/api/user-devices/add-new-device
#  controller: App\Devices\Controller\AddNewDeviceController

#device_gesdinet_jwt_refresh_token:
#  path:       /HomeApp/api/sensor/token/refresh
#  controller: gesdinet.jwtrefreshtoken::refresh
