api_login_check:
    path: /HomeApp/api/login_check

sensor_api_login_check:
  path: /HomeApp/api/device/login_check

gesdinet_jwt_refresh_token:
  path:       /HomeApp/api/token/refresh
  controller: gesdinet.jwtrefreshtoken::refresh

#device_gesdinet_jwt_refresh_token:
#  path:       /HomeApp/api/sensor/token/refresh
#  controller: gesdinet.jwtrefreshtoken::refresh
