parameters:

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name

  ################### Core ############################
  App\User\:
    resource: '../src/User/*'
    exclude: '../src/User/{Traits, DependencyInjection, Entity, Tests}'

  App\User\Controller\:
    resource: '../src/User/Controller'
    tags: [ 'controller.service_arguments' ]


  ######################## Producers ######################################################

  ######################## Consumers ######################################################

  ######################## User Services ######################################################
  App\User\Services\RoomServices\AddNewRoomServiceInterface:
    alias: 'App\User\Services\RoomServices\AddNewRoomService'

  App\User\Services\GroupServices\GroupCheck\GroupCheckServiceInterface:
    alias: 'App\User\Services\GroupServices\GroupCheck\GroupCheckService'

  ######################## New Sensor Creation Services ########################################################

  ######################## Factories ###########################################################################

  ######################## Repositories ########################################################################
  App\User\Repository\ORM\RoomRepositoryInterface:
    alias: 'App\User\Repository\ORM\RoomRepository'

  App\User\Repository\ORM\GroupNameRepositoryInterface:
    alias: 'App\User\Repository\ORM\GroupNameRepository'

  App\User\Repository\ORM\UserInterface\CardViewRepositoryInterface:
    alias: 'App\User\Repository\ORM\UserInterface\CardViewRepository'
######################## End Of Sensors ######################################################################################
