parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  ################### Core ############################
  App\User\:
    resource: '../src/UserInterface/*'
    exclude: '../src/UserInterface/{Traits, DependencyInjection, Entity, Entity/Card, Tests}'

  App\User\Controller\:
    resource: '../src/UserInterface/Controller'
    tags: [ 'controller.service_arguments' ]


  ######################## Producers ######################################################

  ######################## Consumers ######################################################

  ######################## UserInterface Services ######################################################
  App\UserInterface\Services\Cards\CardCreation\CardCreationServiceInterface:
    alias: App\UserInterface\Services\Cards\CardCreation\CardCreationService

  ######################## New Sensor Creation Services ########################################################

  ######################## Factories ###########################################################################

  ######################## Repositories ########################################################################
  App\UserInterface\Repository\ORM\CardRepositories\CardViewRepositoryInterface:
    alias: App\UserInterface\Repository\ORM\CardRepositories\CardViewRepository

  App\UserInterface\Repository\ORM\CardRepositories\CardColourRepositoryInterface:
    alias: App\UserInterface\Repository\ORM\CardRepositories\CardColourRepository

  App\UserInterface\Repository\ORM\CardRepositories\CardStateRepositoryInterface:
    alias: App\UserInterface\Repository\ORM\CardRepositories\CardStateRepository

  App\UserInterface\Repository\ORM\IconsRepositoryInterface:
    alias: App\UserInterface\Repository\ORM\IconsRepository

######################## End Of Sensors ######################################################################################
