# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
imports:
    - { resource: ../src/Devices/services-devices.yaml }
    - { resource: ../src/Sensors/services-esp-sensors.yaml }
    - { resource: ../src/User/services-user.yml }
    - { resource: ../src/UserInterface/services-user_interface.yml }
    - { resource: ../src/Authentication/services-authentication.yaml }

parameters:
services:
    _defaults:
        autowire: true
        autoconfigure: true

    ################### Core ############################
    App\Common\:
        resource: '../src/Common/*'
        exclude: '../src/Common/{API/Traits, Query/Traits, Validation/Traits, DependencyInjection, Entity, Doctrine/Migrations, Tests, Kernel.php}'
