# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
imports:
    - { resource: elasticsearch.yaml }
    - { resource: ../src/Devices/services-devices.yaml }
    - { resource: ../src/Sensors/services-esp-sensors.yaml }
    - { resource: ../src/User/services-user.yml }
    - { resource: ../src/UserInterface/services-user_interface.yml }
    - { resource: ../src/Authentication/services-authentication.yaml }
    - { resource: ../src/ORM/services-orm.yaml }

parameters:
services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
          string $projectDir: '%kernel.project_dir%'

    Symfony\Bridge\Monolog\Handler\ElasticsearchLogstashHandler:
      arguments:
        $endpoint:  '%env(ELASTIC_SEARCH_HOST)%:%env(ELASTIC_SEARCH_PORT)%'
        $index: '%env(ELASTIC_INDEX_LOG)%'
        $client: "@elastica.client"
        $level: !php/const Monolog\Logger::ERROR
        $bubble: true
        $elasticsearchVersion: 8.4.3

  ################### Core ############################
    App\Common\:
      resource: '../src/Common/*'
      exclude:
        - '../src/Common/{Common/API/Traits, Common/Query/Traits, Common/Validation/Traits}'
        - '../src/{DependencyInjection, Kernel.php}'


    App\Common\Logs\ElasticLogger:
      arguments:
#        $logger: '@logger'
        $emergencyIndex: '@elastica.log_index'
        $alertIndex: '@elastica.log_index'
        $criticalIndex: '@elastica.log_index'
        $errorIndex: '@elastica.log_index'
        $warningIndex: '@elastica.log_index'
        $noticeIndex: '@elastica.log_index'
        $infoIndex: '@elastica.log_index'
        $debugIndex: '@elastica.log_index'
        $logIndex: '@elastica.log_index'
#      tags:
#        - { name: monolog.logger, channel: elastic }

##    monolog.elastic:
#      alias: 'App\Common\Logs\ElasticLogger'
#      public: true

#    Psr\Log\LoggerInterface: '@monolog.elastic'
#    monolog.elastica.client:
#        class: Elastica\Client:
#        arguments:
#            $config:
#              servers:
#              - { host: '%env(ELASTIC_SEARCH_HOST)%', port: '%env(ELASTIC_SEARCH_PORT)%', username: '%env(ELASTIC_SEARCH_HTTP_AUTH_USERNAME)%', password: '%env(ELASTIC_SEARCH_HTTP_AUTH_PASSWORD)%', transport: '%env(ELASTIC_TRANSPORT)%', curl: {64: '%env(ELASTIC_SEARCH_SSL_VERIFICATION)%'} }
#              - { host: '%env(ELASTIC_SEARCH_HOST_FAILOVER)%', port: '%env(ELASTIC_SEARCH_PORT_FAILOVER)%', username: '%env(ELASTIC_SEARCH_HTTP_AUTH_USERNAME_FAILOVER)%', password: '%env(ELASTIC_SEARCH_HTTP_AUTH_PASSWORD_FAILOVER)%', transport: '%env(ELASTIC_TRANSPORT_FAILOVER)%', curl: {64: '%env(ELASTIC_SEARCH_SSL_VERIFICATION_FAILOVER)%'} }

    App\Common\Command\ElasticLogIndexCommand:
      arguments:
        $indexMappings: [
          {
            index: '@elastica.log_index',
            mapping: {
              host: 'keyword',
              message: 'text',
              type: 'bucket',
              channel: 'keyword',
              level: 'text',
              monolog_level: 'number',
              context: 'array',
            }
          }
        ]
      tags:
        - { name: 'console.command' }

#    Psr\Log\LoggerInterface:
#      alias: 'App\Common\Logs\ElasticLogger'
#    Symfony\Bridge\Monolog\Handler\ElasticsearchLogstashHandler: ~
#      arguments:
#        $index: 'log'
#        $client: 'Elastica\Client'
#        $level: !php/const Monolog\Logger::DEBUG
#        $bubble: true
#        $elasticsearchVersion: '8.4.3'
