# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
imports:
    - { resource: ../src/Devices/services-devices.yaml }
    - { resource: ../src/Sensors/services-esp-sensors.yaml }
    - { resource: ../src/User/services-user.yml }
    - { resource: ../src/UserInterface/services-user_interface.yml }
    - { resource: ../src/Authentication/services-authentication.yaml }
    - { resource: ../src/Common/services-common.yaml }
    - { resource: elasticsearch.yaml }

parameters:
services:
    _defaults:
        autowire: true
        autoconfigure: true

    ################### Core ############################
    App\Tests\:
        resource: '../src/*'
        exclude: '../src/{Tests, Kernel.php}'
