framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    #http_method_override: true
    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
    cache:
        # Redis
        app: cache.adapter.redis
#        default_redis_provider: '%env(RABBITMQ_URL)%'
#        default_redis_provider: 'redis://redis:6379'
        pools:
            doctrine.result_cache_pool:
                adapter: cache.adapter.redis

            doctrine.system_cache_pool:
                adapter: cache.adapter.redis
    #esi: true
    #fragments: true
    php_errors:
        log: true
