gesdinet_jwt_refresh_token:
#  ttl: 7200
  ttl: 144400
#  user_provider: 'security.user.provider.concrete.app_user_provider'
#  firewall: 'user_api'
  token_parameter_name: refreshToken
#  user_provider: 'api_device_provider'
