gesdinet_jwt_refresh_token:
  ttl: 144400
  token_parameter_name: refreshToken
  refresh_token_class: Gesdinet\JWTRefreshTokenBundle\Entity\RefreshToken
  user_identity_field: 'deviceName'
  ## for more info on config visit: https://github.com/markitosgv/JWTRefreshTokenBundle
