old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'
            lazy: false
            connection_timeout: 3
            read_write_timeout: 3
            heartbeat: 2

        use_socket: true

##### Update Sensor Reading Request ##########
    producers:
        upload_current_reading_sensor_data:
            class: App\ESPDeviceSensor\AMQP\Producers\UpdateCurrentDataProducer
            service_alias: current_sensor_reading_producer
            connection: default
            exchange_options: { name: '%env(UPDATE_SENSOR_EXCHANGE_NAME)%', type: direct }

##### Update Sensor Reading Request ##########
    consumers:
        upload_current_reading_sensor_data:
            connection: default
            exchange_options: { name: '%env(UPDATE_SENSOR_EXCHANGE_NAME)%', type: direct }
            queue_options: { name: '%env(UPDATE_SENSOR_QUEUE_NAME)%' }
            callback: App\ESPDeviceSensor\AMQP\Consumers\UploadCurrentReadingSensorDataConsumer
