security:
    encoders:
        App\User\Entity\User:
            algorithm: auto
        App\Devices\Entity\Devices:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\User\Entity\User
                property: email
        api_device_provider:
            entity:
                class: App\Devices\Entity\Devices
                property: deviceName
        user_and_device:
            chain:
                providers: [ 'app_user_provider', 'api_device_provider' ]
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        device_api:
            pattern: ^/HomeApp/api/device
            stateless: true
            anonymous: true
            provider: 'api_device_provider'
            json_login:
                check_path: /HomeApp/api/device/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

        user_api:
            pattern: ^/HomeApp/api/user
            stateless: true
            anonymous: true
            provider: 'app_user_provider'
            json_login:
                check_path: /HomeApp/api/user/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]


    access_control:
        - { path: ^/HomeApp/api/user/token/refresh, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/HomeApp/api/device/token/refresh, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/HomeApp/api/user/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/HomeApp/api/device/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/HomeApp/WebApp/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/HomeApp/WebApp/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        DEV
        - { path: ^/HomeApp/ssl, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/HomeApp/api/user/csrfToken, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/HomeApp/api/sensors/update/current-reading, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/HomeApp/api/device, roles: ROLE_DEVICE }
        - { path: ^/HomeApp/WebApp/admin, roles: ROLE_ADMIN }
        - { path: ^/HomeApp/WebApp, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/HomeApp/api/user, roles: ROLE_USER }
