
security:
    encoders:
        App\Entity\Core\User:
            algorithm: auto


    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\Core\User
                property: email
        # used to reload user from session & other features (e.g. switch_user)
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern:   ^/HomeApp/api
            stateless: true
            anonymous: true
            json_login:
                check_path:               /HomeApp/api/login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
            guard:
                authenticators:
                - lexik_jwt_authentication.jwt_token_authenticator

        main:
            pattern:   ^/HomeApp/
            anonymous: true
            guard:
                authenticators:
                    - App\Security\UserAuthenticator
            logout:
                path: app_logout


#        main:
#            anonymous: true


    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]


    access_control:
        - { path: ^/HomeApp/api/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/HomeApp/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/HomeApp/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/HomeApp/api/token/refresh, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/HomeApp/ssl, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/HomeApp/csrf, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/HomeApp/, roles: IS_AUTHENTICATED_FULLY }
