# sensors:
#     resource: ../../src/Sensors/Controller
#     type: attribute
#
# devices:
#     resource: ../../src/Devices/Controller
#     type: attribute
#
# user:
#     resource: ../../src/User/Controller
#     type: attribute
#
# user-interface:
#     resource: ../../src/UserInterface/Controller
#     type: attribute

app:
    resource: ../../src/Controller
    type: attribute

kernel:
    resource: ../../src/Kernel.php
    type: attribute
