doctrine:
  dbal:
    default_table_options:
      charset: utf8mb4
      collate: utf8mb4_unicode_ci
    driver: pdo_mysql
    server_version: "%env(DB_SERVER_V)%"
    host:     "%env(DB_HOST)%"
    port:     "%env(MARIADB_INTERNAL_PORT)%"
    dbname:   "%env(DB_NAME)%"
    user:     "%env(DB_USER)%"
    password: "%env(DB_PASSWORD)%"
#    options:
#      1007  : "%env(PRIVATE_KEY)%"
#      1008  : "%env(CLIENT_CERT)%"
#      1009  : "%env(CA_CERT)%"
#      1014  : "%env(SSL_VERIFY_SERVER_CERT)%"

  orm:
    auto_generate_proxy_classes: '%kernel.debug%'
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    metadata_cache_driver: ~
    query_cache_driver:
      type: pool
      pool: doctrine.system_cache_pool
    result_cache_driver:
      type: pool
      pool: doctrine.result_cache_pool
#     mappings:
#       Source:
#         type: attribute
#         dir: '%kernel.project_dir%/src/Sensors/Entity'
#         alias: ESPSensor
#         prefix: App\Sensors\Entity
#       Device:
#         type: attribute
#         dir: '%kernel.project_dir%/src/Devices/Entity'
#         alias: Devices
#         prefix: App\Devices\Entity
#       User:
#         type: attribute
#         dir: '%kernel.project_dir%/src/User/Entity'
#         alias: User
#         prefix: App\User\Entity
#       UserInterface:
#         type: attribute
#         dir: '%kernel.project_dir%/src/UserInterface/Entity'
#         alias: UserInterface
#         prefix: App\UserInterface\Entity
#       Authentication:
#         type: attribute
#         dir: '%kernel.project_dir%/src/Authentication/Entity'
#         alias: Authentication
#         prefix: App\Authentication\Entity
#       Common:
#         type: attribute
#         dir: '%kernel.project_dir%/src/Common/Entity'
#         alias: Common
#         prefix: App\Common\Entity
