old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'
            lazy: false
            connection_timeout: 5
            read_write_timeout: 5
            heartbeat: 5

        use_socket: true

##### Update Sensor Reading Request ##########
    producers:
        upload_current_reading_sensor_data:
            class: App\AMQP\Sensor\Producers\UpdateCurrentDataProducer
            service_alias: current_sensor_reading_producer
            connection: default
            exchange_options: { name: '%env(UPDATE_SENSOR_EXCHANGE_NAME)%', type: direct }
        send_current_reading_sensor_data:
          class: App\AMQP\Sensor\Producers\UploadSwitchSensorProducer
          service_alias: send_current_sensor_reading_producer
          connection: default
          exchange_options: { name: '%env(SEND_SENSOR_UPDATE_EXCHANGE_NAME)%', type: direct }
        send_sensor_data_update:
          class: App\AMQP\Sensor\Producers\UploadSensorDataToDeviceProducer
          service_alias: upload_sensor_data_to_device_producer
          connection: default
          exchange_options: { name: '%env(SEND_SENSOR_DATA_UPDATE_EXCHANGE_NAME)%', type: direct }
        send_device_settings_update:
          class: App\AMQP\Device\Producers\DeviceSettingsUpdateProducer
          service_alias: send_device_settings_update_producer
          connection: default
          exchange_options: { name: '%env(SEND_DEVICE_SETTINGS_UPDATE_EXCHANGE_NAME)%', type: direct }

##### Update Sensor Reading Request ##########
    consumers:
        upload_current_reading_sensor_data:
            connection: default
            exchange_options: { name: '%env(UPDATE_SENSOR_EXCHANGE_NAME)%', type: direct }
            queue_options: { name: '%env(UPDATE_SENSOR_QUEUE_NAME)%' }
            callback: App\AMQP\Sensor\Consumers\ProcessCurrentReadingRequestConsumer
            graceful_max_execution:
              timeout: 900
              exit_code: 10
        send_current_reading_sensor_data:
            connection: default
            exchange_options: { name: '%env(SEND_SENSOR_UPDATE_EXCHANGE_NAME)%', type: direct }
            queue_options: { name: '%env(SEND_SENSOR_UPDATE_QUEUE_NAME)%' }
            callback: App\AMQP\Device\Consumers\SensorSendUpdateReadingRequestConsumer
            graceful_max_execution:
              timeout: 900
              exit_code: 10
        send_sensor_data_update:
            connection: default
            exchange_options: { name: '%env(SEND_SENSOR_DATA_UPDATE_EXCHANGE_NAME)%', type: direct }
            queue_options: { name: '%env(SEND_SENSOR_DATA_UPDATE_QUEUE_NAME)%' }
            callback: App\AMQP\Sensor\Consumers\SensorSendUpdateDataRequestConsumer
            graceful_max_execution:
              timeout: 900
              exit_code: 10
        send_device_settings_update:
          connection: default
          exchange_options: { name: '%env(SEND_DEVICE_SETTINGS_UPDATE_EXCHANGE_NAME)%', type: direct }
          queue_options: { name: '%env(SEND_DEVICE_SETTINGS_UPDATE_QUEUE_NAME)%' }
          callback: App\AMQP\Device\Consumers\DeviceSettingsUpdateConsumer
          graceful_max_execution:
            timeout: 900
            exit_code: 10
