services:
  create_certs:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
    user: "0"
    command: >
      bash -c '
        if [[ ! -f /certs/ca.p12 ]]; then
          bin/elasticsearch-certutil ca --out /certs/ca.p12 --pass "${CA_PASSWORD}";
        fi
        if [[ ! -f /certs/bundle.zip ]]; then
          bin/elasticsearch-certutil cert --silent --in config/certificates/instances.yml --ca /certs/ca.p12 --ca-pass "${CA_PASSWORD}" -out /certs/bundle.zip;
          unzip /certs/bundle.zip -d /certs;
        fi
        chown -R 1000:0 /certs
      '

    environment:
      CA_PASSWORD: ''

    volumes:
      - certs:/certs
      - .:/usr/share/elasticsearch/config/certificates

volumes:
    certs:
